//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometrico2.QPws {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos", ConfigurationName="QPws.ServiceMovimientosSoap")]
    internal interface ServiceMovimientosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarMovimientos(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosv2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarMovimientosv2(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosv2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosv2Async(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosPer" +
            "sonas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarMovimientosPersonas(int idEmpresa, string password, string dni, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosPer" +
            "sonas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosPersonasAsync(int idEmpresa, string password, string dni, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarMovimientosT(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosTAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarNuevoUsuario(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioAsync(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "F", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarNuevoUsuarioF(int idEmpresa, int idSector, string password, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "F", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioFAsync(int idEmpresa, int idSector, string password, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarNuevoUsuariov2(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones, int Habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "v2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarNuevoUsuariov2Async(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones, int Habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "P", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarNuevoUsuarioP(
                    int idEmpresa, 
                    string password, 
                    int idSector, 
                    string Nombre, 
                    string Apellido, 
                    string Documento, 
                    int Legajo, 
                    string nroAsignacion, 
                    string Email, 
                    string Telefono, 
                    string Direccion, 
                    string FotoUsuario, 
                    string Obsevaciones, 
                    string fechaIngreso, 
                    string FechaNacimiento, 
                    int Habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoUsuario" +
            "P", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioPAsync(
                    int idEmpresa, 
                    string password, 
                    int idSector, 
                    string Nombre, 
                    string Apellido, 
                    string Documento, 
                    int Legajo, 
                    string nroAsignacion, 
                    string Email, 
                    string Telefono, 
                    string Direccion, 
                    string FotoUsuario, 
                    string Obsevaciones, 
                    string fechaIngreso, 
                    string FechaNacimiento, 
                    int Habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsBajaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsBajaUsuario(int idEmpresa, string password, int Legajo, int idSectorBaja, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsBajaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsBajaUsuarioAsync(int idEmpresa, string password, int Legajo, int idSectorBaja, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsEliminarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsEliminarUsuario(int idEmpresa, string password, int Legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsEliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsEliminarUsuarioAsync(int idEmpresa, string password, int Legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarMovimiento(int idEmpresa, string password, int idSector, int idUsuario, string sensorId, string fechaHoraMov, int idTipoMov, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarMovimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarMovimientoAsync(int idEmpresa, string password, int idSector, int idUsuario, string sensorId, string fechaHoraMov, int idTipoMov, string Obsevaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarNovedades(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedadesT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarNovedadesT(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedadesT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesTAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedadesP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarNovedadesP(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarNovedadesP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesPAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosMob" +
            "ile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarMovimientosMobile(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarMovimientosMob" +
            "ile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosMobileAsync(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarRutaMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarRutaMobile(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarRutaMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarRutaMobileAsync(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTurnos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarTurnos(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTurnos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarTurnosAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTurnosFlexible" +
            "s", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarTurnosFlexibles(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTurnosFlexible" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarTurnosFlexiblesAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarConteo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarConteo(int idEmpresa, string password, int idSector, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarConteo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarConteoAsync(int idEmpresa, string password, int idSector, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarUsuarios(int idEmpresa, string password, string Legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarUsuariosAsync(int idEmpresa, string password, string Legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsConsultaLegajoFecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string wsConsultaLegajoFecha(int idEmpresa, string password, string Legajo, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsConsultaLegajoFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<string> wsConsultaLegajoFechaAsync(int idEmpresa, string password, string Legajo, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarSectores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarSectores(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarSectores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarSectoresAsync(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoSector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int wsInsertarNuevoSector(int idEmpresa, string password, int idSector, string Nombre, int idTimeZone, string Geo, int idIdioma, int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsInsertarNuevoSector", ReplyAction="*")]
        System.Threading.Tasks.Task<int> wsInsertarNuevoSectorAsync(int idEmpresa, string password, int idSector, string Nombre, int idTimeZone, string Geo, int idIdioma, int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarTimeZone(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarTimeZone", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarTimeZoneAsync(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarIdiomas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarIdiomas(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarIdiomas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarIdiomasAsync(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarPaises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarPaises(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarPaises", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarPaisesAsync(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarConceptosLiqui" +
            "dacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarConceptosLiquidacion(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarConceptosLiqui" +
            "dacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarConceptosLiquidacionAsync(int idEmpresa, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReportePresentismo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsReportePresentismo(int idEmpresa, string password, string legajo, string fechaDesde, string fechaHasta, string cuit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReportePresentismo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsReportePresentismoAsync(int idEmpresa, string password, string legajo, string fechaDesde, string fechaHasta, string cuit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsLiquidacionConceptos" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsLiquidacionConceptos(int idEmpresa, string password, int idUsuario, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsLiquidacionConceptos" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsLiquidacionConceptosAsync(int idEmpresa, string password, int idUsuario, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarHuellasUsuario" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarHuellasUsuario(int idEmpresa, string password, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarHuellasUsuario" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarHuellasUsuarioAsync(int idEmpresa, string password, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReporteFacturacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsReporteFacturacion(int idEmpresa, string password, string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReporteFacturacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsReporteFacturacionAsync(int idEmpresa, string password, string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReporteLlegadasTarde" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsReporteLlegadasTarde(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, string idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsReporteLlegadasTarde" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsReporteLlegadasTardeAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, string idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarAsignacionSkil" +
            "ls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarAsignacionSkills(int idEmpresa, string password, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarAsignacionSkil" +
            "ls", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarAsignacionSkillsAsync(int idEmpresa, string password, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarAsignacionSkil" +
            "lsKN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarAsignacionSkillsKN(int idEmpresa, string password, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarAsignacionSkil" +
            "lsKN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarAsignacionSkillsKNAsync(int idEmpresa, string password, string fechaDesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarRestriccionesU" +
            "suarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsListarRestriccionesUsuarios(int idEmpresa, string password, string Legajo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qpweb.com.ar/QPWsMovimientos/ServiceMovimientos/wsListarRestriccionesU" +
            "suarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsListarRestriccionesUsuariosAsync(int idEmpresa, string password, string Legajo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ServiceMovimientosSoapChannel : Biometrico2.QPws.ServiceMovimientosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ServiceMovimientosSoapClient : System.ServiceModel.ClientBase<Biometrico2.QPws.ServiceMovimientosSoap>, Biometrico2.QPws.ServiceMovimientosSoap {
        
        public ServiceMovimientosSoapClient() {
        }
        
        public ServiceMovimientosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMovimientosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMovimientosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMovimientosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet wsListarMovimientos(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida) {
            return base.Channel.wsListarMovimientos(idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida) {
            return base.Channel.wsListarMovimientosAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida);
        }
        
        public System.Data.DataSet wsListarMovimientosv2(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida) {
            return base.Channel.wsListarMovimientosv2(idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosv2Async(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int marcaExporta, int marcaMov, int TipoSalida) {
            return base.Channel.wsListarMovimientosv2Async(idEmpresa, password, Legajo, fechaDesde, fechaHasta, marcaExporta, marcaMov, TipoSalida);
        }
        
        public System.Data.DataSet wsListarMovimientosPersonas(int idEmpresa, string password, string dni, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarMovimientosPersonas(idEmpresa, password, dni, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosPersonasAsync(int idEmpresa, string password, string dni, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarMovimientosPersonasAsync(idEmpresa, password, dni, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarMovimientosT(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarMovimientosT(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosTAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarMovimientosTAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public int wsInsertarNuevoUsuario(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones) {
            return base.Channel.wsInsertarNuevoUsuario(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioAsync(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones) {
            return base.Channel.wsInsertarNuevoUsuarioAsync(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones);
        }
        
        public int wsInsertarNuevoUsuarioF(int idEmpresa, int idSector, string password, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones) {
            return base.Channel.wsInsertarNuevoUsuarioF(idEmpresa, idSector, password, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioFAsync(int idEmpresa, int idSector, string password, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones) {
            return base.Channel.wsInsertarNuevoUsuarioFAsync(idEmpresa, idSector, password, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones);
        }
        
        public int wsInsertarNuevoUsuariov2(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones, int Habilitado) {
            return base.Channel.wsInsertarNuevoUsuariov2(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones, Habilitado);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarNuevoUsuariov2Async(int idEmpresa, string password, int idSector, string Nombre, string Apellido, string Documento, int Legajo, string Email, string Telefono, string Direccion, string FotoUsuario, string Obsevaciones, int Habilitado) {
            return base.Channel.wsInsertarNuevoUsuariov2Async(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, Email, Telefono, Direccion, FotoUsuario, Obsevaciones, Habilitado);
        }
        
        public int wsInsertarNuevoUsuarioP(
                    int idEmpresa, 
                    string password, 
                    int idSector, 
                    string Nombre, 
                    string Apellido, 
                    string Documento, 
                    int Legajo, 
                    string nroAsignacion, 
                    string Email, 
                    string Telefono, 
                    string Direccion, 
                    string FotoUsuario, 
                    string Obsevaciones, 
                    string fechaIngreso, 
                    string FechaNacimiento, 
                    int Habilitado) {
            return base.Channel.wsInsertarNuevoUsuarioP(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, nroAsignacion, Email, Telefono, Direccion, FotoUsuario, Obsevaciones, fechaIngreso, FechaNacimiento, Habilitado);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarNuevoUsuarioPAsync(
                    int idEmpresa, 
                    string password, 
                    int idSector, 
                    string Nombre, 
                    string Apellido, 
                    string Documento, 
                    int Legajo, 
                    string nroAsignacion, 
                    string Email, 
                    string Telefono, 
                    string Direccion, 
                    string FotoUsuario, 
                    string Obsevaciones, 
                    string fechaIngreso, 
                    string FechaNacimiento, 
                    int Habilitado) {
            return base.Channel.wsInsertarNuevoUsuarioPAsync(idEmpresa, password, idSector, Nombre, Apellido, Documento, Legajo, nroAsignacion, Email, Telefono, Direccion, FotoUsuario, Obsevaciones, fechaIngreso, FechaNacimiento, Habilitado);
        }
        
        public int wsBajaUsuario(int idEmpresa, string password, int Legajo, int idSectorBaja, string Obsevaciones) {
            return base.Channel.wsBajaUsuario(idEmpresa, password, Legajo, idSectorBaja, Obsevaciones);
        }
        
        public System.Threading.Tasks.Task<int> wsBajaUsuarioAsync(int idEmpresa, string password, int Legajo, int idSectorBaja, string Obsevaciones) {
            return base.Channel.wsBajaUsuarioAsync(idEmpresa, password, Legajo, idSectorBaja, Obsevaciones);
        }
        
        public int wsEliminarUsuario(int idEmpresa, string password, int Legajo) {
            return base.Channel.wsEliminarUsuario(idEmpresa, password, Legajo);
        }
        
        public System.Threading.Tasks.Task<int> wsEliminarUsuarioAsync(int idEmpresa, string password, int Legajo) {
            return base.Channel.wsEliminarUsuarioAsync(idEmpresa, password, Legajo);
        }
        
        public int wsInsertarMovimiento(int idEmpresa, string password, int idSector, int idUsuario, string sensorId, string fechaHoraMov, int idTipoMov, string Obsevaciones) {
            return base.Channel.wsInsertarMovimiento(idEmpresa, password, idSector, idUsuario, sensorId, fechaHoraMov, idTipoMov, Obsevaciones);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarMovimientoAsync(int idEmpresa, string password, int idSector, int idUsuario, string sensorId, string fechaHoraMov, int idTipoMov, string Obsevaciones) {
            return base.Channel.wsInsertarMovimientoAsync(idEmpresa, password, idSector, idUsuario, sensorId, fechaHoraMov, idTipoMov, Obsevaciones);
        }
        
        public System.Data.DataSet wsListarNovedades(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarNovedades(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarNovedadesAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarNovedadesT(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarNovedadesT(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesTAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarNovedadesTAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Data.DataSet wsListarNovedadesP(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarNovedadesP(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarNovedadesPAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, int idSector) {
            return base.Channel.wsListarNovedadesPAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Data.DataSet wsListarMovimientosMobile(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarMovimientosMobile(idEmpresa, password, idDispositvo, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarMovimientosMobileAsync(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarMovimientosMobileAsync(idEmpresa, password, idDispositvo, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarRutaMobile(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarRutaMobile(idEmpresa, password, idDispositvo, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarRutaMobileAsync(int idEmpresa, string password, string idDispositvo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarRutaMobileAsync(idEmpresa, password, idDispositvo, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarTurnos(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarTurnos(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarTurnosAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarTurnosAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarTurnosFlexibles(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarTurnosFlexibles(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarTurnosFlexiblesAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarTurnosFlexiblesAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarConteo(int idEmpresa, string password, int idSector, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarConteo(idEmpresa, password, idSector, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarConteoAsync(int idEmpresa, string password, int idSector, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarConteoAsync(idEmpresa, password, idSector, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarUsuarios(int idEmpresa, string password, string Legajo) {
            return base.Channel.wsListarUsuarios(idEmpresa, password, Legajo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarUsuariosAsync(int idEmpresa, string password, string Legajo) {
            return base.Channel.wsListarUsuariosAsync(idEmpresa, password, Legajo);
        }
        
        public string wsConsultaLegajoFecha(int idEmpresa, string password, string Legajo, string fecha) {
            return base.Channel.wsConsultaLegajoFecha(idEmpresa, password, Legajo, fecha);
        }
        
        public System.Threading.Tasks.Task<string> wsConsultaLegajoFechaAsync(int idEmpresa, string password, string Legajo, string fecha) {
            return base.Channel.wsConsultaLegajoFechaAsync(idEmpresa, password, Legajo, fecha);
        }
        
        public System.Data.DataSet wsListarSectores(int idEmpresa, string password) {
            return base.Channel.wsListarSectores(idEmpresa, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarSectoresAsync(int idEmpresa, string password) {
            return base.Channel.wsListarSectoresAsync(idEmpresa, password);
        }
        
        public int wsInsertarNuevoSector(int idEmpresa, string password, int idSector, string Nombre, int idTimeZone, string Geo, int idIdioma, int idPais) {
            return base.Channel.wsInsertarNuevoSector(idEmpresa, password, idSector, Nombre, idTimeZone, Geo, idIdioma, idPais);
        }
        
        public System.Threading.Tasks.Task<int> wsInsertarNuevoSectorAsync(int idEmpresa, string password, int idSector, string Nombre, int idTimeZone, string Geo, int idIdioma, int idPais) {
            return base.Channel.wsInsertarNuevoSectorAsync(idEmpresa, password, idSector, Nombre, idTimeZone, Geo, idIdioma, idPais);
        }
        
        public System.Data.DataSet wsListarTimeZone(int idEmpresa, string password) {
            return base.Channel.wsListarTimeZone(idEmpresa, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarTimeZoneAsync(int idEmpresa, string password) {
            return base.Channel.wsListarTimeZoneAsync(idEmpresa, password);
        }
        
        public System.Data.DataSet wsListarIdiomas(int idEmpresa, string password) {
            return base.Channel.wsListarIdiomas(idEmpresa, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarIdiomasAsync(int idEmpresa, string password) {
            return base.Channel.wsListarIdiomasAsync(idEmpresa, password);
        }
        
        public System.Data.DataSet wsListarPaises(int idEmpresa, string password) {
            return base.Channel.wsListarPaises(idEmpresa, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarPaisesAsync(int idEmpresa, string password) {
            return base.Channel.wsListarPaisesAsync(idEmpresa, password);
        }
        
        public System.Data.DataSet wsListarConceptosLiquidacion(int idEmpresa, string password) {
            return base.Channel.wsListarConceptosLiquidacion(idEmpresa, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarConceptosLiquidacionAsync(int idEmpresa, string password) {
            return base.Channel.wsListarConceptosLiquidacionAsync(idEmpresa, password);
        }
        
        public System.Data.DataSet wsReportePresentismo(int idEmpresa, string password, string legajo, string fechaDesde, string fechaHasta, string cuit) {
            return base.Channel.wsReportePresentismo(idEmpresa, password, legajo, fechaDesde, fechaHasta, cuit);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsReportePresentismoAsync(int idEmpresa, string password, string legajo, string fechaDesde, string fechaHasta, string cuit) {
            return base.Channel.wsReportePresentismoAsync(idEmpresa, password, legajo, fechaDesde, fechaHasta, cuit);
        }
        
        public System.Data.DataSet wsLiquidacionConceptos(int idEmpresa, string password, int idUsuario, string fechaDesde, string fechaHasta) {
            return base.Channel.wsLiquidacionConceptos(idEmpresa, password, idUsuario, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsLiquidacionConceptosAsync(int idEmpresa, string password, int idUsuario, string fechaDesde, string fechaHasta) {
            return base.Channel.wsLiquidacionConceptosAsync(idEmpresa, password, idUsuario, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarHuellasUsuario(int idEmpresa, string password, int idUsuario) {
            return base.Channel.wsListarHuellasUsuario(idEmpresa, password, idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarHuellasUsuarioAsync(int idEmpresa, string password, int idUsuario) {
            return base.Channel.wsListarHuellasUsuarioAsync(idEmpresa, password, idUsuario);
        }
        
        public System.Data.DataSet wsReporteFacturacion(int idEmpresa, string password, string periodo) {
            return base.Channel.wsReporteFacturacion(idEmpresa, password, periodo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsReporteFacturacionAsync(int idEmpresa, string password, string periodo) {
            return base.Channel.wsReporteFacturacionAsync(idEmpresa, password, periodo);
        }
        
        public System.Data.DataSet wsReporteLlegadasTarde(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, string idSector) {
            return base.Channel.wsReporteLlegadasTarde(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsReporteLlegadasTardeAsync(int idEmpresa, string password, string Legajo, string fechaDesde, string fechaHasta, string idSector) {
            return base.Channel.wsReporteLlegadasTardeAsync(idEmpresa, password, Legajo, fechaDesde, fechaHasta, idSector);
        }
        
        public System.Data.DataSet wsListarAsignacionSkills(int idEmpresa, string password, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarAsignacionSkills(idEmpresa, password, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarAsignacionSkillsAsync(int idEmpresa, string password, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarAsignacionSkillsAsync(idEmpresa, password, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarAsignacionSkillsKN(int idEmpresa, string password, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarAsignacionSkillsKN(idEmpresa, password, fechaDesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarAsignacionSkillsKNAsync(int idEmpresa, string password, string fechaDesde, string fechaHasta) {
            return base.Channel.wsListarAsignacionSkillsKNAsync(idEmpresa, password, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataSet wsListarRestriccionesUsuarios(int idEmpresa, string password, string Legajo) {
            return base.Channel.wsListarRestriccionesUsuarios(idEmpresa, password, Legajo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsListarRestriccionesUsuariosAsync(int idEmpresa, string password, string Legajo) {
            return base.Channel.wsListarRestriccionesUsuariosAsync(idEmpresa, password, Legajo);
        }
    }
}
